### ISSUE TITLE
Error when running prepare_mesh.py

### ISSUE THREAD

**Issue by trminh89** [mveres01/grasping#3]
Hi, I got this error when doing the first step (`python prepare_mesh.py`):

Error:

> Traceback (most recent call last):
>   File "prepare_mesh.py", line 104, in <module>
>     main(config_object_dir, config_mesh_dir)
>   File "prepare_mesh.py", line 87, in main
>     processed = process_mesh(mesh_path, mesh_output_dir)
>   File "prepare_mesh.py", line 46, in process_mesh
>     mesh_properties = mesh.mass_properties()
> TypeError: 'dict' object is not callable

I'm not sure what wrong here. Any suggestion?
Thanks!

**Comment by mveres01** [comment]
Try changing
```mesh_properties = mesh.mass_properties()```
to
```mesh_properties = mesh.mass_properties```

It looks like something might have changed in the trimesh library where it went from a callable function to simply a dictionary
